// Generated by CoffeeScript 2.3.2
(function() {
  var BussinessContext, Context, MongoDao, ObjectId;

  Context = require("./Context");

  MongoDao = require("./MongoDao");

  ObjectId = require('mongodb').ObjectId;

  /*
   * 业务上下文接口
   */
  BussinessContext = class BussinessContext extends Context {
    selectList(param, callback) {
      var dao;
      if (!(param && param.col && param.filter)) {
        return callback("invalid param");
      }
      dao = new MongoDao(__b_config.dbInfo, {
        epcos: param.col
      });
      return dao.epcos[param.col].selectList(param.filter, callback);
    }

    insert(param, callback) {
      var dao;
      if (!(param && param.col && param.data)) {
        return callback("invalid param");
      }
      dao = new MongoDao(__b_config.dbInfo, {
        epcos: param.col
      });
      return dao.epcos[param.col].insert(param.data, callback);
    }

    update(param, callback) {
      var dao;
      if (!(param && param.col && param.filter)) {
        return callback("invalid param");
      }
      dao = new MongoDao(__b_config.dbInfo, {
        epcos: param.col
      });
      return dao.epcos[param.col].update(param.filter, param.setter, callback);
    }

    addOrUpdate(param, callback) {
      var dao;
      if (!(param && param.col && param.data)) {
        return callback("invalid param");
      }
      dao = new MongoDao(__b_config.dbInfo, {
        epcos: param.col
      });
      return dao.epcos[param.col].addOrUpdate(param.data, callback);
    }

    delete(param, callback) {
      var dao;
      if (!(param && param.col && param.filter)) {
        return callback("invalid param");
      }
      dao = new MongoDao(__b_config.dbInfo, {
        epcos: param.col
      });
      return dao.epcos[param.col].delete(param.filter, callback);
    }

    selectBySortOrSkipOrLimit(param, callback) {
      var dao;
      if (!(param && param.col && param.filter && +param.limit)) {
        return callback("invalid param");
      }
      if (param.skip !== 0 && !param.skip) {
        return callback("invalid param");
      }
      dao = new MongoDao(__b_config.dbInfo, {
        epcos: param.col
      });
      return dao.epcos[param.col].selectBySortOrSkipOrLimit(param.filter, param.sort, +param.skip, +param.limit, callback);
    }

    selectBySortOrLimit(param, callback) {
      var dao;
      if (!(param && param.col && param.filter)) {
        return callback("invalid param");
      }
      dao = new MongoDao(__b_config.dbInfo, {
        epcos: param.col
      });
      return dao.epcos[param.col].selectBySortOrLimit(param.filter, param.sort, +param.limit || -1, callback);
    }

    count(param, callback) {
      var dao;
      if (!(param && param.col && param.filter)) {
        return callback("invalid param");
      }
      dao = new MongoDao(__b_config.dbInfo, {
        epcos: param.col
      });
      return dao.epcos[param.col].count(param.filter, callback);
    }

  };

  module.exports = BussinessContext;

}).call(this);
