// Generated by CoffeeScript 2.3.2
(function() {
  var BussinessContext, Context;

  Context = require("./Context");

  /*
   * 业务上下文接口
   */
  BussinessContext = class BussinessContext extends Context {
    selectList(param, callback) {
      var dao;
      if (!(param && param.col && param.filter)) {
        return callback("invalid param");
      }
      dao = new MongoDao(__b_config.dbInfo, {
        epcos: param.col
      });
      return dao.epcos[param.col].selectList(param.filter, callback);
    }

    insert(param, callback) {
      var dao;
      if (!(param && param.col && param.data)) {
        return callback("invalid param");
      }
      dao = new MongoDao(__b_config.dbInfo, {
        epcos: param.col
      });
      return dao.epcos[param.col].insert(param.data, callback);
    }

    update(param, callback) {
      var dao;
      if (!(param && param.col && param.filter)) {
        return callback("invalid param");
      }
      dao = new MongoDao(__b_config.dbInfo, {
        epcos: param.col
      });
      return dao.epcos[param.col].update(param.filter, param.setter, callback);
    }

    delete(param, callback) {
      var dao;
      if (!(param && param.col && param.filter)) {
        return callback("invalid param");
      }
      dao = new MongoDao(__b_config.dbInfo, {
        epcos: param.col
      });
      return dao.epcos[param.col].delete(param.filter, callback);
    }

  };

  module.exports = BussinessContext;

}).call(this);
