// Generated by CoffeeScript 2.3.2
(function() {
  var CleanHandler, ExecHandler, Handler, LOG;

  Handler = require("./Handler");

  ExecHandler = require("./ExecHandler");

  LOG = LoggerUtil.getLogger("CleanHandler");

  CleanHandler = class CleanHandler extends Handler {
    handle(item, callback) {
      LOG.info("切图");
      return callback();
    }

  };

  module.exports = CleanHandler;

}).call(this);
