// Generated by CoffeeScript 2.3.2
(function() {
  var ConvertHandler, Handler, LOG;

  Handler = require("./Handler");

  LOG = LoggerUtil.getLogger("ConvertHandler");

  ConvertHandler = class ConvertHandler extends Handler {
    handle(callback) {
      LOG.info("图片转换");
      return callback();
    }

  };

  module.exports = ConvertHandler;

}).call(this);
