// Generated by CoffeeScript 2.3.2
(function() {
  var CutPictureHandler, ExecHandler, Handler, LOG;

  Handler = require("./Handler");

  ExecHandler = require("./ExecHandler");

  LOG = LoggerUtil.getLogger("CutPictureHandler");

  CutPictureHandler = class CutPictureHandler extends Handler {
    handle(callback) {
      LOG.info("切图");
      return callback();
    }

  };

  module.exports = CutPictureHandler;

}).call(this);
