// Generated by CoffeeScript 2.3.2
(function() {
  var DBProxy, LOG, Proxy;

  Proxy = require("./Proxy");

  LOG = LoggerUtil.getLogger("DBProxy");

  /*
   * 数据库操作层代理
   */
  DBProxy = class DBProxy extends Proxy {
    constructor(target) {
      super(target);
    }

    proxy(f) {
      var that;
      that = this;
      if (f.name === "connect") {
        return function() {
          return f.apply(that.target, arguments);
        };
      }
      return function() {
        var callback, params, startTime;
        [...params] = arguments;
        callback = params.pop();
        startTime = moment();
        params.push(function() {
          var endTime;
          endTime = moment();
          LOG.info(`${that.target.constructor.name}.${f.name}:${JSON.stringify(params[0])}  --${endTime - startTime}ms`);
          return callback.apply(this, arguments);
        });
        return f.apply(that.target, params);
      };
    }

  };

  module.exports = DBProxy;

}).call(this);
