// Generated by CoffeeScript 2.3.2
(function() {
  var DBProxy, LOG, Proxy;

  Proxy = require("./Proxy");

  LOG = LoggerUtil.getLogger("DBProxy");

  /*
   * 数据库操作层代理
   */
  DBProxy = class DBProxy extends Proxy {
    constructor(target) {
      super(target);
    }

    proxy(f) {
      var that;
      that = this;
      if (f.name === "connect") {
        return function() {
          return f.apply(that.target, arguments);
        };
      }
      return function() {
        var callback, e, p, paramStr, params, startTime;
        [...params] = arguments;
        callback = params.pop();
        startTime = moment();
        paramStr = (function() {
          var i, len, results;
          results = [];
          for (i = 0, len = params.length; i < len; i++) {
            p = params[i];
            results.push(JSON.stringify(p));
          }
          return results;
        })();
        params.push(function() {
          var endTime;
          endTime = moment();
          LOG.info(`${that.target.constructor.name}.${f.name}:${paramStr.join(",")}  --${endTime - startTime}ms`);
          return callback.apply(this, arguments);
        });
        try {
          return f.apply(that.target, params);
        } catch (error) {
          e = error;
          LOG.error(`${that.target.constructor.name}.${f.name}:${paramStr.join(",")}  --${moment() - startTime}ms\n${e.stack}`);
          return callback(e);
        }
      };
    }

  };

  module.exports = DBProxy;

}).call(this);
