// Generated by CoffeeScript 2.3.2
(function() {
  /*
   * 下载策略
   */
  var DownStrategy, Istrategy;

  Istrategy = require("./Istrategy");

  DownStrategy = (function() {
    class DownStrategy extends Istrategy {
      constructor(execOrderList) {
        var handler, i, j, len, moduleName;
        super();
        if (execOrderList && execOrderList instanceof Array) {
          for (i = j = 0, len = execOrderList.length; j < len; i = ++j) {
            moduleName = execOrderList[i];
            if (!(moduleName || moduleName !== "")) {
              continue;
            }
            handler = require('./' + moduleName);
            this.handlerList.push(new HandlerProxy(new handler(this.data)));
          }
        }
      }

      execute(callback) {
        var arr;
        if (this.handlerList.length === 0) {
          callback();
        }
        arr = this.handlerList.map((handler) => {
          handler.target.data = this.data;
          return function(next) {
            return handler.execute.call(handler, next);
          };
        });
        return async.series(arr, callback);
      }

    };

    /*
     * 策略的业务数据，操作者都有权访问并修改
     * 一个操作者将访问上一位操作者处理完的数据
     * 操作者通过verify方法来检查数据并决定是否执行操作
     */
    DownStrategy.prototype.data = {};

    //# 操作者名称列表，策略会根据这个顺序调用操作者
    DownStrategy.prototype.handlerList = [];

    return DownStrategy;

  }).call(this);

  module.exports = DownStrategy;

}).call(this);
