// Generated by CoffeeScript 2.3.2
(function() {
  var AfterDownStrategy, Context, DownStrategy, DownloadContext, LOG, ProDownStrategy, StrategyContext;

  Context = require("./Context");

  StrategyContext = require("./StrategyContext");

  ProDownStrategy = require("./ProDownStrategy");

  DownStrategy = require("./DownStrategy");

  AfterDownStrategy = require("./AfterDownStrategy");

  global.StrategyProxy = require("./StrategyProxy");

  global.HandlerProxy = require("./HandlerProxy");

  LOG = LoggerUtil.getLogger("DownloadContext");

  DownloadContext = class DownloadContext extends Context {
    execute(param, socket, callback) {
      var afterDownHandle, beforeDownHandle, cb, downHandle, proxy;
      // 下载前动作（有序）
      beforeDownHandle = ["LoadConfigHandler", "ScanHandler", "ParseDirHandler"];
      // 下载动作（有序）
      downHandle = ["LoadOriginalHandler", "ConvertHandler", "ParseProHandler", "CutImageHandler", "CutBillHandler", "EnterEntityHandler", "OCRHandler", "SavePicInfoHandler"];
      // 下载后动作
      afterDownHandle = ["SaveOutputStatisHandler", "CleanHandler"];
      cb = function(err) {
        var proxy, ref, ref1, strategyContext;
        if (err) {
          return callback(err);
        }
        proxy = new StrategyProxy(new DownStrategy(downHandle, socket));
        proxy.io = {
          socket: socket
        };
        strategyContext = new StrategyContext(proxy);
        strategyContext.strategy.target.data = this.data;
        socket.emit("total", (ref = this.data) != null ? (ref1 = ref.originals) != null ? ref1.length : void 0 : void 0);
        return setTimeout(() => {
          return strategyContext.execute(this.data.originals, (err) => {
            var afterDownStrategy, ref2, ref3;
            if (err) {
              return callback(err, (ref2 = this.data) != null ? (ref3 = ref2.originals) != null ? ref3.length : void 0 : void 0);
            }
            afterDownStrategy = new StrategyContext(new StrategyProxy(new AfterDownStrategy(afterDownHandle, socket)));
            afterDownStrategy.strategy.target.data = this.data;
            return afterDownStrategy.execute((err) => {
              var ref4, ref5;
              return callback(err, (ref4 = this.data) != null ? (ref5 = ref4.originals) != null ? ref5.length : void 0 : void 0);
            });
          });
        }, 0);
      };
      proxy = new StrategyProxy(new ProDownStrategy(beforeDownHandle, socket));
      proxy.io = {
        socket: socket
      };
      return new StrategyContext(proxy).execute(param, cb);
    }

  };

  module.exports = DownloadContext;

}).call(this);
