// Generated by CoffeeScript 2.3.2
(function() {
  var Context, DownStrategy, DownloadContext, LOG, ProDownStrategy, StrategyContext;

  Context = require("./Context");

  StrategyContext = require("./StrategyContext");

  ProDownStrategy = require("./ProDownStrategy");

  DownStrategy = require("./DownStrategy");

  global.StrategyProxy = require("./StrategyProxy");

  global.HandlerProxy = require("./HandlerProxy");

  LOG = LoggerUtil.getLogger("DownloadContext");

  DownloadContext = class DownloadContext extends Context {
    execute(param, socket, callback) {
      var beforeDownHandle, cb, downHandle, proxy, start;
      // 下载前动作（有序）
      beforeDownHandle = ["LoadConfigHandler", "ScanHandler", "ParseDirHandler"];
      // 下载动作（有序）
      downHandle = ["LoadImageHandler", "ConvertHandler", "ParseProHandler", "CutImageHandler", "CutBillHandler", "EnterEntityHandler", "OCRHandler", "SavePicInfoHandler", "CleanHandler"];
      // 下载后动作
      // afterDownHandle = ["", "", "", ""]
      start = moment();
      socket && socket.emit(0, `本次下载开始于：${start.format("YYYY-MM-DD HH:mm:ss")}`);
      LOG.info(`本次下载开始于：${start.format("YYYY-MM-DD HH:mm:ss")}`);
      cb = function() {
        var proxy, strategyContext;
        proxy = new StrategyProxy(new DownStrategy(downHandle, socket));
        proxy.io = {
          socket: socket
        };
        strategyContext = new StrategyContext(proxy);
        strategyContext.strategy.target.data = this.data;
        return strategyContext.execute(function() {
          var endTime;
          endTime = moment();
          LOG.info(`本次下载结束于：${endTime.format("YYYY-MM-DD HH:mm:ss")} --${endTime - start}ms`);
          socket && socket.emit(1, `本次下载结束于：${endTime.format("YYYY-MM-DD HH:mm:ss")} --${endTime - start}ms`);
          return callback();
        });
      };
      proxy = new StrategyProxy(new ProDownStrategy(beforeDownHandle, socket));
      proxy.io = {
        socket: socket
      };
      return new StrategyContext(proxy).execute(param, cb);
    }

  };

  module.exports = DownloadContext;

}).call(this);
