// Generated by CoffeeScript 2.3.2
(function() {
  // 配置加载者
  var Handler, LOG, LoadConfigHandler;

  Handler = require("./Handler");

  LOG = LoggerUtil.getLogger("LoadConfigHandler");

  LoadConfigHandler = class LoadConfigHandler extends Handler {
    handle(callback) {
      var dao, start, that;
      that = this;
      dao = new MongoDao(__b_config.dbInfo, {
        epcos: ["deploy"]
      });
      start = moment();
      return dao.epcos.deploy.selectOne({
        type: "proj",
        projName: argv.project
      }, function(err, doc) {
        if (err) {
          return callback(err);
        }
        that.data.deploy = {};
        if (!doc) {
          return callback();
        }
        that.data.deploy.project = doc;
        return dao.epcos.deploy.selectList({
          project: doc._id.toString(),
          state: "1"
        }, function(err, docs) {
          if (err) {
            return callback(err);
          }
          that.data.deploy.images = [];
          that.data.deploy.bills = [];
          that.data.deploy.fields = [];
          docs.forEach && docs.forEach(function(doc) {
            switch (doc.type) {
              case "image":
                return that.data.deploy.images.push(doc);
              case "bill":
                return that.data.deploy.bills.push(doc);
              case "field":
                return that.data.deploy.fields.push(doc);
            }
          });
          LOG.info(`加载${argv.project}项目配置 --${moment() - start}ms`);
          return callback();
        });
      });
    }

  };

  module.exports = LoadConfigHandler;

}).call(this);
