// Generated by CoffeeScript 2.3.2
(function() {
  var AsyncLock, LOG, LockHandler, MAX_PENDING, MAX_WAITTIME, Proxy, RETRIES, RETRY, domainReentrant, lockFile, lock_dir;

  Proxy = require("./Proxy");

  AsyncLock = require("async-lock");

  lockFile = require("lockfile");

  LOG = LoggerUtil.getLogger("LockHandler");

  MAX_WAITTIME = 120000; // 最大等待时间

  MAX_PENDING = 1000; // 最大处理任务

  domainReentrant = true; // 同域是否可重用

  RETRY = 100; // 重新尝试等待时间

  RETRIES = 100; // 重新尝试次数

  lock_dir = "/run/lock/temp"; // 使用文件锁机制，临时文件存放处

  mkdirp.sync(lock_dir);

  LockHandler = class LockHandler {
    constructor(param) {
      var opt1;
      param = param || {};
      opt1 = {
        timeout: param.timeout || MAX_WAITTIME,
        maxPending: param.pending || MAX_PENDING,
        domainReentrant: !!param.reentrant || domainReentrant
      };
      this.opts = {
        wait: param.timeout || MAX_WAITTIME,
        retryWait: param.retry || RETRY,
        retries: param.retries || RETRIES
      };
      param.pollPeriod && (this.opts.pollPeriod = param.pollPeriod);
      param.stale && (this.opts.stale = param.stale);
      this.asyncLock = new AsyncLock(opt1);
      this.lockFile = lockFile;
    }

  };

  module.exports = LockHandler;

}).call(this);
