// Generated by CoffeeScript 2.3.2
(function() {
  /*
   * 日志模块
   */
  var LoggerUtil, configLog, log4js;

  log4js = require("log4js");

  configLog = require("../config/config-log.json");

  log4js.configure(configLog);

  LoggerUtil = class LoggerUtil {
    /*
     * 默认全局使用default类别
     * 通过传入类名，生成该类类别的日志对象
     */
    getLogger(category) {
      if (!(category || category === "" || category === "default")) {
        return log4js.getLogger("default");
      } else {
        configLog.categories[category] = configLog.categories.default;
        log4js.configure(configLog);
        return log4js.getLogger(category);
      }
    }

    useLogger(app, logger) {
      return app != null ? typeof app.use === "function" ? app.use(log4js.connectLogger(logger || this.getLogger(), {
        format: '[:remote-addr :method :url :status :response-timems][:referrer HTTP/:http-version :user-agent]'
      })) : void 0 : void 0;
    }

  };

  module.exports = new LoggerUtil();

}).call(this);
