// Generated by CoffeeScript 2.3.2
(function() {
  var DBHandler, MongoDao;

  DBHandler = require("./DBHandler");

  MongoDao = class MongoDao {
    constructor(config, cont) {
      var col, i, k, len, perfix, postfix, v;
      if (!config) {
        throw "未进行数据库配置";
      }
      if (!cont) {
        throw "请传入实例化库和集合";
      }
      perfix = `mongodb://${config.username}:${config.password}@${config.hostName}:${config.port}/`;
      postfix = `?${config.auth}`;
      for (k in cont) {
        v = cont[k];
        this[k] = {};
        for (i = 0, len = v.length; i < len; i++) {
          col = v[i];
          this[k][col] = new DBHandler(perfix + k + postfix, col, config.DB_OPTS);
        }
      }
    }

  };

  module.exports = MongoDao;

}).call(this);
