// Generated by CoffeeScript 2.3.2
(function() {
  var ExecHandler, Handler, LOG, OCRHandler;

  Handler = require("./Handler");

  ExecHandler = require("./ExecHandler");

  LOG = LoggerUtil.getLogger("OCRHandler");

  OCRHandler = class OCRHandler extends Handler {
    handle(callback) {
      var that;
      that = this;
      if (!this.data.enterEntitys) {
        LOG.warn(`${argv.project}：没有录入的内容`);
        return callback(null);
      }
      return async.eachLimit(this.data.enterEntitys, 50, function(enterEntity, cb) {
        var file_path;
        file_path = enterEntity.path + enterEntity.img_name;
        return fs.readFile(file_path, function(err) {
          var en, i, len, ref, result;
          if (err) {
            enterEntity.stage = "error";
            enterEntity.remark = err;
            return cb(null);
          }
          result = {};
          enterEntity.stage = "op1";
          ref = enterEntity.enter;
          for (i = 0, len = ref.length; i < len; i++) {
            en = ref[i];
            delete en.src_type;
            // en.value = result[en.field_id]
            en.value["ocr"] = "123";
          }
          return cb(null);
        });
      }, callback);
    }

  };

  module.exports = OCRHandler;

}).call(this);
