// Generated by CoffeeScript 2.3.2
(function() {
  var ExecHandler, Handler, LOG, OCRHandler;

  Handler = require("./Handler");

  ExecHandler = require("./ExecHandler");

  LOG = LoggerUtil.getLogger("OCRHandler");

  OCRHandler = class OCRHandler extends Handler {
    handle(item, callback) {
      LOG.info("机器识读图片信息");
      return callback();
    }

  };

  module.exports = OCRHandler;

}).call(this);
