// Generated by CoffeeScript 2.3.2
(function() {
  var BussinessContext, LOG, OutputStatisContext;

  BussinessContext = require('./BussinessContext');

  LOG = LoggerUtil.getLogger("OutputStatisContext");

  OutputStatisContext = class OutputStatisContext extends BussinessContext {
    getOutPutPageData(param, callback) {
      if (param.isCount) {
        return this.count({
          col: "outputData",
          filter: param.filter
        }, callback);
      } else if (param.isPage) {
        return this.selectBySortOrSkipOrLimit({
          col: "outputData",
          filter: param.filter,
          sort: param.sort || null,
          skip: +param.skip,
          limit: +param.limit
        }, callback);
      } else {
        return this.selectList({
          col: "outputData",
          filter: param.filter
        }, callback);
      }
    }

  };

  module.exports = OutputStatisContext;

}).call(this);
