// Generated by CoffeeScript 2.3.2
(function() {
  var Handler, LOG, ParseProHandler;

  Handler = require("./Handler");

  LOG = LoggerUtil.getLogger("ParseProHandler");

  ParseProHandler = class ParseProHandler extends Handler {
    handle(callback) {
      LOG.info("保单解析");
      return callback();
    }

  };

  module.exports = ParseProHandler;

}).call(this);
