// Generated by CoffeeScript 2.3.2
(function() {
  var ExecHandler, Handler, LOG, ParseProHandler;

  Handler = require("./Handler");

  ExecHandler = require("./ExecHandler");

  LOG = LoggerUtil.getLogger("ParseProHandler");

  ParseProHandler = class ParseProHandler extends Handler {
    handle(item, callback) {
      LOG.info("解析项目");
      return callback();
    }

  };

  module.exports = ParseProHandler;

}).call(this);
