// Generated by CoffeeScript 2.3.2
(function() {
  var Handler, LOG, ParseProHandler;

  Handler = require("./Handler");

  LOG = LoggerUtil.getLogger("ParseProHandler");

  ParseProHandler = class ParseProHandler extends Handler {
    handle(param, callback) {
      if (!param || !param.data) {
        LOG.warn(`${argv.project}：没有需要解析文件名的内容`);
        return callback("没有需要解析文件名的内容");
      }
      return callback(null, param);
    }

  };

  module.exports = ParseProHandler;

}).call(this);
