// Generated by CoffeeScript 2.3.2
(function() {
  var Handler, LOG, ParseDirHandler;

  Handler = require("./Handler");

  LOG = LoggerUtil.getLogger("ParseDirHandler");

  ParseDirHandler = class ParseDirHandler extends Handler {
    handle(callback) {
      var i, image, len, lines, ref, reg;
      if (!this.data.deploy.images) {
        LOG.warn(`${argv.project}：没有进行图片配置`);
        return callback(null);
      }
      this.data.originals = [];
      ref = this.data.deploy.images;
      for (i = 0, len = ref.length; i < len; i++) {
        image = ref[i];
        if (/^dir/.test(image.d_url)) {
          reg = new RegExp("(\\S+)\\s+(\\S+)\\s+(\\S+)\\s+(\\S+)$");
        } else {
          reg = new RegExp("(\\S+)\\s+(\\S+\\s+\\S+\\s+\\S+)\\s+(\\S+)$");
        }
        lines = image.lines ? image.lines : [];
        if ("string" === typeof lines) {
          lines = lines.split(/[\r\n]+/);
        }
        LOG.info(`${image.d_url}目录解析: ${lines.length} 行`);
        // 反向排序，一般 ftp 返回结果，旧文档在后面
        lines.reverse();
        lines.forEach((line) => {
          var arr, size, upload_at;
          line = line.trim();
          arr = reg.exec(line);
          if (!/(png|jpg|pdf|tif)$/.test(line)) {
            return;
          }
          if (/^dir/.test(image.d_url)) {
            size = parseInt(arr[3].replace(/,/g, ""));
            arr[3] = arr[4];
            upload_at = moment(arr[1] + " " + arr[2], "YYYY/MM/DD HH:mm").format("YYYYMMDDHHmmss");
          } else {
            size = parseInt(arr[1]);
            upload_at = moment(arr[2], "MMM D HH:mm").format("YYYYMMDDHHmmss");
          }
          return this.data.originals.push({
            deploy_id: image._id.toString(),
            type: "original",
            code: image.code,
            img_name: arr[3],
            d_url: image.d_url,
            s_url: `${image.s_url}/image/`,
            size: size,
            upload_at: upload_at
          });
        });
      }
      return callback();
    }

  };

  module.exports = ParseDirHandler;

}).call(this);
