// Generated by CoffeeScript 2.3.2
(function() {
  var ConfigContext, ExecHandler, LOG, ObjectId, Router, bodyParser, cookieParser, express, multer, session;

  express = require("express");

  bodyParser = require('body-parser');

  cookieParser = require("cookie-parser");

  session = require("express-session");

  multer = require("multer");

  ObjectId = require('mongodb').ObjectId;

  ConfigContext = require("./ConfigContext");

  ExecHandler = require("./ExecHandler");

  LOG = LoggerUtil.getLogger("Router");

  Router = class Router {
    constructor() {
      this.preRouter();
    }

    preRouter() {
      app.use('/js', express.static(path.join(workspace, 'web/js')));
      app.use('/css', express.static(path.join(workspace, 'web/css')));
      app.use('/fonts', express.static(path.join(workspace, 'web/fonts')));
      app.use('/images', express.static(path.join(workspace, 'web/images')));
      app.set('view engine', 'html');
      app.use('/pages', function(req, res, next) {
        res.setHeader("Content-Type", "text/html");
        return next();
      });
      app.use('/pages', express.static(path.join(workspace, 'web/pages')));
      /*
       * 开启跨域，便于接口访问.
       */
      return app.all('*', function(req, res, next) {
        res.header('Access-Control-Allow-Origin', '*'); //控制访问来源：所有
        res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept'); //访问控制允许报头 X-Requested-With: xhr请求 
        res.header('Access-Control_Allow-Metheds', 'GET, POST, PUT, DELETE, OPTIONS'); //访问控制允许方法 
        res.header('X-Powered-By', 'nodejs'); //自定义头信息，表示服务端用nodejs 
        res.header('Content-Type', 'application/json;charset=utf-8');
        return next();
      });
    }

    router() {
      var configRouter, storage, upload;
      app.use(bodyParser.json());
      app.use(bodyParser.urlencoded({
        extended: true
      }));
      app.use(cookieParser());
      configRouter = express.Router(); // 配置请求路由
      
      //# 获取配置信息
      configRouter.get("/getDeploy", function(req, res) {
        var configContext, param;
        configContext = new ConfigContext();
        param = Object.keys(req.query).length === 0 ? req.body : req.query;
        return configContext.getDeploy(param, function(err, conf) {
          if (err) {
            LOG.error(err);
            return res.json(null);
          } else {
            return res.json(conf);
          }
        });
      });
      //# 保存配置信息
      configRouter.post("/saveDeploy", function(req, res) {
        var configContext, data, filter, type, verify;
        configContext = new ConfigContext();
        data = Object.keys(req.query).length === 0 ? req.body : req.query;
        type = data.type;
        verify = {
          db: "epcos",
          col: "deploy"
        };
        if (type === "proj") {
          verify.filter;
          verify.filter = {
            $or: [
              {
                projName: data.projName
              },
              {
                projCode: data.projCode
              }
            ]
          };
        } else {
          filter = {
            type: type
          };
          if (type === "image") {
            filter["project"] = data.project;
          }
          if (type === "bill") {
            filter["project"] = data.project;
            filter["image"] = data.image;
          }
          if (type === "field") {
            filter["project"] = data.project;
            filter["image"] = data.image;
            filter["bill"] = data.bill;
          }
          filter.code = data.code;
          verify.filter = filter;
        }
        return configContext.exist(verify, function(err, exist) {
          if (err) {
            LOG.error(err);
            return res.json(null);
          } else if (exist) {
            return res.json("exist");
          } else {
            return configContext.saveDeploy(data, function(err) {
              if (err) {
                LOG.error(err);
              }
              return res.json(null);
            });
          }
        });
      });
      //# 更新配置信息
      configRouter.post("/updateDeploy", function(req, res) {
        var configContext, data;
        configContext = new ConfigContext();
        data = Object.keys(req.query).length === 0 ? req.body : req.query;
        return configContext.updateDeploy({
          _id: data._id
        }, data, function(err) {
          if (err) {
            LOG.error(err);
          }
          return res.json(null);
        });
      });
      //# 删除图片配置样例及裙带信息
      configRouter.post("/delImageTempl", function(req, res) {
        var configContext, data;
        configContext = new ConfigContext();
        data = Object.keys(req.query).length === 0 ? req.body : req.query;
        if (!data.delFile) {
          return res.json(null);
        }
        if (!data.img) {
          return res.json("error");
        }
        return async.each(data.delFile, function(path, cb) {
          return fs.unlink(path, function(err) {
            var filter;
            if (err) {
              LOG.error(err);
              return cb("error");
            }
            filter = {
              project: data.img.project,
              image: data.img._id,
              src_img: path
            };
            return configContext.getDeploy(filter, function(err, docs) {
              if (err) {
                LOG.error(err);
                return cb("error");
              }
              return async.each(docs, function(doc, cb1) {
                return fs.unlink(doc.img_path, function(err) {
                  if (err) {
                    LOG.error(err);
                    return cb1("error");
                  }
                  return configContext.deleteDeploy(doc, function(err) {
                    if (err) {
                      LOG.error(err);
                      return cb1("error");
                    }
                    return cb1(null);
                  });
                });
              }, cb);
            });
          });
        }, function(err) {
          return res.json(err);
        });
      });
      //# 删除配置信息
      configRouter.post("/deleteDeploy", function(req, res) {
        var configContext, data, filter, type;
        configContext = new ConfigContext();
        data = Object.keys(req.query).length === 0 ? req.body : req.query;
        type = data.type;
        filter = {};
        if (type === "proj") {
          filter.$or = [
            {
              _id: ObjectId(data._id)
            },
            {
              project: data._id
            }
          ];
        }
        if (type === "image") {
          filter.$or = [
            {
              _id: ObjectId(data._id)
            },
            {
              project: data.project,
              image: data._id
            }
          ];
        }
        if (type === "bill") {
          filter.$or = [
            {
              _id: ObjectId(data._id)
            },
            {
              project: data.project,
              image: data.image,
              bill: data._id
            }
          ];
        }
        if (type === "field") {
          filter._id = data._id;
        }
        if (Object.keys(filter).length === 0) {
          return res.json(null);
        }
        return configContext.deleteDeploy(filter, function(err) {
          if (err) {
            LOG.error(err);
          }
          return res.json(null);
        });
      });
      // 文件上传
      storage = multer.diskStorage({
        destination: function(req, file, cb) {
          var data, dir;
          data = Object.keys(req.query).length === 0 ? req.body : req.query;
          dir = data.dir ? `./web/images/template/${data.dir}` : './web/images/template/';
          if (data.rmdir) {
            return fs.rmdir(data.rmdir, function(err) {
              if (err) {
                LOG.error(err);
              }
              return mkdirp(dir, function(err) {
                if (err) {
                  LOG.error(err);
                }
                return cb(err, dir);
              });
            });
          } else {
            return mkdirp(dir, function(err) {
              if (err) {
                LOG.error(err);
              }
              return cb(err, dir);
            });
          }
        },
        filename: function(req, file, cb) {
          var data, filename, str;
          data = Object.keys(req.query).length === 0 ? req.body : req.query;
          str = file.originalname.split('.');
          filename = data.filename ? data.filename : Date.now() + '.' + str[1];
          return cb(null, filename);
        }
      });
      upload = multer({
        storage: storage
      });
      configRouter.post("/uploadFile", upload.array("file", 1), function(req, res, next) {
        if (req.files && req.files.length > 0) {
          return res.json(req.files[0].path);
        } else {
          return res.json(null);
        }
      });
      // 文件删除
      configRouter.post("/delFile", function(req, res) {
        var data;
        data = Object.keys(req.query).length === 0 ? req.body : req.query;
        if (data) {
          if (data.type === "file") {
            return fs.unlink(data.path, function(err) {
              if (err) {
                LOG.error(err);
              }
              return res.json(err);
            });
          } else {
            return Utils.rmdir(data.path, function(err) {
              if (err) {
                LOG.error(err);
              }
              return res.json(err);
            });
          }
        } else {
          return res.json(null);
        }
      });
      // 文件名修改
      configRouter.get("/moddir", function(req, res) {
        var data, f_arr, i, t_arr;
        data = Object.keys(req.query).length === 0 ? req.body : req.query;
        if (data) {
          f_arr = data.from.split("\\");
          t_arr = data.to.split("\\");
          i = -1;
          return async.eachSeries(f_arr, function(name, cb) {
            var m_arr;
            i++;
            if (name !== t_arr[i]) {
              m_arr = t_arr.slice(0, i);
              return fs.exists(m_arr.join("\\") + "\\" + t_arr[i], function(exist) {
                if (exist) {
                  return cb("exist");
                }
                return fs.rename(m_arr.join("\\") + "\\" + name, m_arr.join("\\") + "\\" + t_arr[i], cb);
              });
            } else {
              return cb(null);
            }
          }, function(err) {
            if (err) {
              LOG.error(err);
            }
            res.setHeader(200);
            return res.json(err);
          });
        }
      });
      // 样例切图
      configRouter.post("/crop", function(req, res) {
        var data;
        data = Object.keys(req.query).length === 0 ? req.body : req.query;
        return fs.exists(data.cut_path + "\\" + data.data.code + ".jpg", function(exist) {
          if (exist) {
            return res.json("exist");
          }
          return mkdirp(data.cut_path, function(err) {
            var cut_cmd, e, exec, options;
            if (err) {
              LOG.error(err);
              return res.json("create dir error");
            }
            options = {
              src: data.src,
              dst: data.cut_path + "\\" + data.data.code + ".jpg",
              x0: data.data.x0,
              y0: data.data.y0,
              x1: data.data.x1,
              y1: data.data.y1
            };
            cut_cmd = "gmic -v - %(src)s -crop[-1] %(x0)s,%(y0)s,%(x1)s,%(y1)s -o[-1] %(dst)s";
            try {
              cut_cmd = sprintf.sprintf(cut_cmd, options);
            } catch (error) {
              e = error;
              LOG.error(e.stack);
              return res.json("create dir error");
            }
            exec = new ExecHandler().queue_exec(1);
            return exec(cut_cmd, function(err, stdout, stderr, spent) {
              if (err) {
                LOG.error(err);
                return res.json("crop error");
              }
              stdout = `${stdout}`.trim();
              stderr = `${stderr}`.trim();
              if (stdout.length > 0) {
                LOG.info(stdout);
              }
              if (stderr.length > 0) {
                LOG.info(stderr);
              }
              LOG.info(`${options.src} => ${options.dst} ${spent}ms`);
              return res.json("success");
            });
          });
        });
      });
      return app.use("/config", configRouter);
    }

  };

  module.exports = Router;

}).call(this);
