// Generated by CoffeeScript 2.3.2
(function() {
  var ExecHandler, Handler, LOG, SaveOutputStatisHandler;

  Handler = require("./Handler");

  ExecHandler = require("./ExecHandler");

  LOG = LoggerUtil.getLogger("SaveOutputStatisHandler");

  SaveOutputStatisHandler = class SaveOutputStatisHandler extends Handler {
    handle() {
      var callback, dao, params;
      [...params] = arguments;
      callback = params.pop();
      if (this.data && this.data.outputStatis) {
        dao = new MongoDao(__b_config.dbInfo, {
          epcos: ["outputData"]
        });
        return dao.epcos.outputData.insert(this.data.outputStatis, function(err) {
          if (err) {
            LOG.error(err);
          }
          return typeof callback === "function" ? callback(err) : void 0;
        });
      } else {
        LOG.warn("没有产量统计对象");
        return typeof callback === "function" ? callback(null) : void 0;
      }
    }

  };

  module.exports = SaveOutputStatisHandler;

}).call(this);
