// Generated by CoffeeScript 2.3.2
(function() {
  var ExecHandler, Handler, LOG, SavePicInfoHandler;

  Handler = require("./Handler");

  ExecHandler = require("./ExecHandler");

  LOG = LoggerUtil.getLogger("SavePicInfoHandler");

  SavePicInfoHandler = class SavePicInfoHandler extends Handler {
    handle(callback) {
      LOG.info("保存图片信息");
      return callback();
    }

  };

  module.exports = SavePicInfoHandler;

}).call(this);
