// Generated by CoffeeScript 2.3.2
(function() {
  var ExecHandler, Handler, LOG, ScanHandler;

  Handler = require("./Handler");

  ExecHandler = require("./ExecHandler");

  LOG = LoggerUtil.getLogger("ScanHandler");

  ScanHandler = class ScanHandler extends Handler {
    handle(callback) {
      var cmd, cmd_display, exec, ref, start_at, that;
      that = this;
      cmd = (ref = this.data.conf.remote) != null ? ref.scan : void 0;
      cmd_display = cmd != null ? cmd.replace(/\s+\-u\s+\S+/g, " -u '***:***'") : void 0; //不打印密码
      LOG.info(`开始扫描 remote.scan: ${cmd_display}`);
      start_at = moment();
      if (!cmd) {
        return callback(new Error(`项目配置未定义 [${conf.project}]: remote.scan`), "");
      }
      exec = new ExecHandler().queue_exec();
      return exec(cmd, function(error, lines, stderr) {
        lines = ("" + lines).trim().split(/[\r\n]+/);
        LOG.info(`扫描结束, ${lines.length} 行, ${moment() - start_at}ms`);
        that.data.lines = lines;
        return callback();
      });
    }

  };

  module.exports = ScanHandler;

}).call(this);
