// Generated by CoffeeScript 2.3.2
(function() {
  var LOG, Proxy, StrategyProxy;

  Proxy = require("./Proxy");

  LOG = LoggerUtil.getLogger("StrategyProxy");

  /*
   * 策略代理类
   */
  StrategyProxy = class StrategyProxy extends Proxy {
    constructor(target) {
      super(target);
    }

    proxy(f) {
      var that;
      that = this;
      return function() {
        var callback, cb, params, startTime;
        //# 默认只代理策略的执行方法，并只添加日志记录能力
        if (f.name === "execute") {
          LOG.info(`策略${that.target.constructor.name}.${f.name}开始执行`);
          startTime = moment();
          [...params] = arguments;
          callback = params.pop();
          cb = () => {
            var endTime;
            endTime = moment();
            LOG.info(`策略${that.target.constructor.name}.${f.name}执行结束 --${endTime - startTime}ms`);
            return typeof callback === "function" && callback.apply(this, arguments);
          };
          params.push(cb);
          return f.apply(that.target, params);
        } else {
          return f.apply(that.target, arguments);
        }
      };
    }

  };

  module.exports = StrategyProxy;

}).call(this);
