// Generated by CoffeeScript 2.3.2
(function() {
  var BussinessContext, LOG, SysConfigContext;

  BussinessContext = require('./BussinessContext');

  LOG = LoggerUtil.getLogger("SysConfigContext");

  SysConfigContext = class SysConfigContext extends BussinessContext {};

  module.exports = SysConfigContext;

}).call(this);
