// Generated by CoffeeScript 2.3.2
(function() {
  var BussinessContext, EnterContext, LOG, ObjectId, SysConfigContext, exec;

  BussinessContext = require('./BussinessContext');

  EnterContext = require("./EnterContext");

  exec = require("child_process").exec;

  ObjectId = require('mongodb').ObjectId;

  LOG = LoggerUtil.getLogger("SysConfigContext");

  SysConfigContext = class SysConfigContext extends BussinessContext {
    accessControl(param, callback) {}

  };

  module.exports = SysConfigContext;

}).call(this);
