// Generated by CoffeeScript 2.3.2
(function() {
  var Context, UserContext, crypto;

  crypto = require("crypto");

  Context = require("./Context");

  UserContext = class UserContext extends Context {
    login(param, callback) {
      var dao;
      dao = new MongoDao(__b_config.dbInfo, {
        sys_user: ["users"]
      });
      return dao.sys_user.users.selectOne({
        username: param.usercode
      }, function(err, doc) {
        var e, password;
        if (err) {
          LOG.info(err.stack);
          return callback(null, "error");
        } else if (!doc) {
          return callback(null, "no exist");
        } else {
          try {
            password = crypto.createHash("md5").update(param.password).digest("hex");
          } catch (error) {
            e = error;
            callback(null, "error");
          }
          if (password === doc.password) {
            return callback(null, "success");
          } else {
            return callback(null, "failed");
          }
        }
      });
    }

  };

  module.exports = UserContext;

}).call(this);
