// Generated by CoffeeScript 2.3.2
(function() {
  var Context, UserContext, crypto;

  crypto = require("crypto");

  Context = require("./Context");

  UserContext = class UserContext extends Context {
    login(param, callback) {
      var dao;
      dao = new MongoDao(__b_config.dbInfo, {
        sys_user: ["users"]
      });
      return dao.sys_user.users.selectOne({
        username: param.usercode
      }, function(err, doc) {
        var e, password;
        if (err) {
          LOG.info(err.stack);
          return callback(null, "error");
        } else if (!doc) {
          return callback(null, "no exist");
        } else {
          try {
            password = crypto.createHash("md5").update(param.password).digest("hex");
          } catch (error) {
            e = error;
            callback(null, "error");
          }
          if (password === doc.password) {
            return callback(null, "success", doc);
          } else {
            return callback(null, "failed");
          }
        }
      });
    }

    getUsers(param, callback) {
      var dao;
      dao = new MongoDao(__b_config.dbInfo, {
        sys_user: ["users"]
      });
      if (!param) {
        return callback(null);
      }
      param.filter || (param.filter = {});
      if (param.count) {
        return dao.sys_user.users.count(param.filter, callback);
      } else if (param.skip) {
        return dao.sys_user.users.selectBySortOrSkipOrLimit(param.filter, param.sort, +param.skip, +param.limit, callback);
      } else {
        return callback(null);
      }
    }

  };

  module.exports = UserContext;

}).call(this);
