// Generated by CoffeeScript 2.3.2
(function() {
  /*
   * 工具类
   */
  var Utils, getOPropNms;

  Utils = {};

  Utils.getOPropNms = getOPropNms = Object.getOwnPropertyNames;

  module.exports = Utils;

}).call(this);
